### PR TITLE
Introduce url extension to help avoid force unwrapping for static urls and add unit test for changed model

### PR DESCRIPTION
**Pull request by DanKorkelia**
Hi 👋
Happy new year.

Wanted to provide a tiny contribution to your excellent project wit this little addition to help avoid force unwrapping static URLs. 
Also added a unit test for model. Not sure what the exact policy is but thought it might be helpful.

Best wishes
Dan

### CODE REVIEW

**Review by ericlewis — APPROVED** [review]
I see you read swift by sundell ;)

Thanks! This is great.

**Comment by ericlewis** [comment]
One note though: I would prefer the arg be named staticString instead as that clarifies what is going on.

**Comment by DanKorkelia** [comment]
Hey! Happy to chip in. Glad you liked the change. Think I might have lifted this from Paul H actually but I do read John's blog on regular basis too :)  I'll update the argument no problem.

**Review by ericlewis — CHANGES_REQUESTED** [review]
I meant the extension should be used like URL(staticString: "") but you're still anonymizing the actual argument. Delete the _ and update the call sites :)

**Comment by ericlewis** [comment]
> I meant the extension should be used like URL(staticString: "") but you're still anonymizing the actual argument. Delete the _ and update the call sites :)

My reasoning for this is because we don't have to know about the extension- we can read in the call sites to understand why URL is behaving differently instead of tracking back to the extension. I think when extending "native" types it's always important to be clear what is going on when it's used places too.

**Comment by DanKorkelia** [comment]
That's a good argument for more clarity I'm happy with that. I slightly rushed to change the name and only realised you were after explicated name for call site. I will update.

**Pull request merged**
